-- LEVEL 2 (JOINS)

-- Q13. What is the total revenue generated by each product?
-- select products.product_id , products.product_name ,sum(total) as total_revenue from products join sales 
-- on products.product_id=sales.product_id group by product_id order by total_revenue desc;

-- Q14. What is the average rating for each product? 
-- select products.product_id,products.product_name , avg(rating) as avg_rating from sales 
-- join products on sales.product_id = products.product_id group by product_id order by avg_rating desc;

-- Q15. Which are the top 5 highest revenue generating products?
-- select products.product_id , products.product_name ,sum(total) as total_revenue from products join sales 
-- on products.product_id=sales.product_id group by product_id order by total_revenue desc limit 5;

-- Q16. How much total revenue is generated by each city?
-- select city.city_id,city.city_name,sum(sales.total) as total_revenue from city join customers on city.city_id=customers.city_id 
-- join sales on customers.customer_id=sales.customer_id group by city.city_id,city.city_name order by total_revenue desc ;

-- Q17. How many unique customers are there in each city?
-- select  city.city_name , count(distinct customers.customer_id) as total_customers from customers join city on
-- customers.city_id = city.city_id group by city.city_id order by total_customers desc; 

-- Q18. What is the average order value (AOV) for each city?
-- select city.city_id , city.city_name , avg(sales.total) as avg_order_value from sales join customers on sales.customer_id=customers.customer_id 
-- join city on city.city_id=customers.city_id group by city.city_name , city.city_id order by avg_order_value desc ;

-- Q19. What is the average customer rating in each city?
-- select city.city_id , city.city_name , avg(sales.rating) as avg_rating from sales join customers on sales.customer_id=customers.customer_id 
-- join city on city.city_id=customers.city_id group by city.city_name , city.city_id order by avg_rating desc ;

-- Q20. What is the total revenue generated by each product in each city?
-- select city.city_name , products.product_name, sum(sales.total) as total_revenue from sales join products
-- on sales.product_id = products.product_id join customers on sales.customer_id = customers.customer_id 
-- join city on city.city_id = customers.city_id group by city.city_name , products.product_name order by total_revenue desc;

-- Q21. Which product is most popular in each city based on total revenue?
-- select city.city_name , products.product_name , sum(sales.total) as total_revenue from sales join products on
-- sales.product_id = products.product_id join customers on sales.customer_id = customers.customer_id 
-- join city on city.city_id = customers.city_id group by city.city_name , products.product_name order by city.city_name ,total_revenue desc ;

-- Q22. What is the total revenue and average rating for each product ?
-- select products.product_name,sum(sales.total) as total_revenue , avg(sales.rating) as avg_rating from sales join products on 
-- sales.product_id = products.product_id group by products.product_name order by total_revenue desc; 

-- Q23. What is the total revenue and estimated rent for each city?
-- select city.city_name , city.estimated_rent , sum(sales.total) as total_revenue from sales join customers on 
-- sales.customer_id = customers.customer_id join city on city.city_id = customers.city_id group by city.city_name,city.estimated_rent 
-- order by total_revenue desc;

-- Q24. Which cities have higher revenue compared to their estimated rent?
-- select city.city_name, sum(sales.total) as total_revenue,city.estimated_rent,(sum(sales.total) - city.estimated_rent) as revenue_minus_rent
-- from sales join customers on sales.customer_id = customers.customer_id join city on customers.city_id = city.city_id
-- group by city.city_name, city.estimated_rent having sum(sales.total) > city.estimated_rent order by revenue_minus_rent desc;


