-- LEVEL 1 (BASIC QUERIES)

-- Q1. How many total sales transactions are there?
-- select count(*) as total_transactions from sales;

-- Q2. What is the total revenue generated by the business?
-- select sum(total) as total_revenue from sales ; 

-- Q3. How many unique customers have made purchases?
-- select count(distinct customer_id) as total_customers from sales;

-- Q4. How many products are available in the product catalog?
-- select count(distinct product_id) as total_products from products;

-- Q5. How many cities does the business operate in? 
-- select count(*) as total_cities from city;

-- Q6. What is the average order value (AOV)?
-- select avg(total) as average_total_value from sales ; 

-- Q7. What are the minimum, maximum, and average product prices?
-- select min(price) as minimum_price , max(price) as maximum_price , avg(price) as average_price from products ;

-- Q8. What is the overall average customer rating? 
-- select avg(rating) as average_rating from sales ;

-- Q9. What are the highest and lowest ratings given in sales transactions?
-- select max(rating) as highest_rating , min(rating) as lowest_rating from sales ;

-- Q10. What is the population of each city?
-- select city_name , population from city ;

-- Q11. What are the highest and lowest bill amounts recorded?
-- select max(total) as highest_billamount , min(total) as lowest_billamount from sales ; 

-- Q12. What is the total estimated rent across all cities?
-- select sum(estimated_rent) as total_estimated_rent from city ;

